import Head from "next/head";
import Carosel from "../components/carosel";
import { Stack } from "@mui/material";
import { ISlider } from "../definitions/slider.def";

interface IProps {
  slides: ISlider[];
}

export default function Home({ slides }: IProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          minWidth: "100%",
          minHeight: "100vh",
          backgroundColor: "black",
        }}
      >
        <Stack
          width={"100%"}
          height={"100vh"}
          alignItems={"center"}
          justifyContent={"center"}
        >
          <Carosel />
        </Stack>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {},
  };
}
